### ISSUE TITLE
missing method textDocument/completion

### ISSUE THREAD

**Issue by mcepl** [dcermak/rpm-spec-language-server#16]
When trying completing string `Buil` with `omnifunc` in neovim I get:

```
[WARN][2023-11-07 22:14:22] .../lua/vim/lsp.lua:101 \
"method textDocument/completion is not supported by any of the servers registered for the current buffer"
```

Also, in the log:

```
Registered "textDocument/completion" with options "CompletionOptions(trigger_characters=['%'], all_commit_characters=None, resolve_provider=None, completion_item=None, work_done_progress=None)"
```

Does it mean that it completes only macros? Hmm, that doesn’t work either: completing `%auto` gets the same error message.

**Comment by dcermak** [comment]
It does currently only complete macros, that part is correct. However, I don't really understand why it shouldn't complete anything at all. Do you have more log files by any chance?

**Comment by mcepl** [comment]
Somehow got fixed.
