### ISSUE TITLE
Add reference on https://github.com/openlawlibrary/pygls/blob/main/Implementations.md

### ISSUE THREAD

**Issue by mcepl** [dcermak/rpm-spec-language-server#41]
It would be probably more appropriate if the link was added by @dcermak , so I am not doing anything behind his back.

**Comment by dcermak** [comment]
Let's do this once we have a release out

**Comment by mcepl** [comment]
And what’s missing from us being able to do the release? Or would you make a milestone, please?

**Comment by dcermak** [comment]
Fixed via https://github.com/openlawlibrary/pygls/pull/466
