### ISSUE TITLE
Use data from `specfile.constants` instead of parsing markdown docs

### ISSUE THREAD

**Issue by gotmax23** [dcermak/rpm-spec-language-server#44]
The project apparently uses the `spec.md` file from the RPM docs as the source of truth for specfile keywords. If possible, It would be more reliable to use the data from [`specfile.constants`](https://github.com/packit/specfile/blob/main/specfile/constants.py). The specfile project has a script that uses pyparsing to parse the RPM C code and generate this data automatically.

**Comment by dcermak** [comment]
We opted for parsing `spec.md` because that allows us to display the documentation as well and not just the keywords. But I guess we could merge both approaches :thinking:
